In [ ]:
!pip install wikipedia

Requirement already satisfied: wikipedia in /usr/local/lib/python3.12/dist-packages (1.4.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2025.10.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (4.15.0)

In [ ]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files
import wikipedia
import requests
from bs4 import BeautifulSoup
import re

In [ ]:
df=pd.read_csv('Video_Games_Sales_Raw.csv')
df.sample(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
11350,11352,Metal Slug Advance,GBA,2004.0,Shooter,Ignition Entertainment,0.06,0.02,0.0,0.00,0.08
2609,2611,WCW Mayhem,N64,1999.0,Fighting,Electronic Arts,0.63,0.15,0.0,0.01,0.79
16383,16386,Pilot Academy,PSP,2006.0,Simulation,Rising Star Games,0.00,0.01,0.0,0.00,0.01
12208,12210,Cold Stone Creamery: Scoop It Up,Wii,2009.0,Misc,Zoo Games,0.06,0.00,0.0,0.00,0.07
8204,8206,NBA Starting Five,PS2,NaN,Sports,Unknown,0.09,0.07,0.0,0.02,0.18

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [ ]:
df[df['Year'].isnull()]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
179,180,Madden NFL 2004,PS2,NaN,Sports,Electronic Arts,4.26,0.26,0.01,0.71,5.23
377,378,FIFA Soccer 2004,PS2,NaN,Sports,Electronic Arts,0.59,2.36,0.04,0.51,3.49
431,432,LEGO Batman: The Videogame,Wii,NaN,Action,Warner Bros. Interactive Entertainment,1.86,1.02,0.00,0.29,3.17
470,471,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,NaN,1.57,1.02,0.00,0.41,3.00
607,608,Space Invaders,2600,NaN,Shooter,Atari,2.36,0.14,0.00,0.03,2.53
...,...,...,...,...,...,...,...,...,...,...,...
16307,16310,Freaky Flyers,GC,NaN,Racing,Unknown,0.01,0.00,0.00,0.00,0.01
16327,16330,Inversion,PC,NaN,Shooter,Namco Bandai Games,0.01,0.00,0.00,0.00,0.01
16366,16369,Hakuouki: Shinsengumi Kitan,PS3,NaN,Adventure,Unknown,0.01,0.00,0.00,0.00,0.01
16427,16430,Virtua Quest,GC,NaN,Role-Playing,Unknown,0.01,0.00,0.00,0.00,0.01
16493,16496,The Smurfs,3DS,NaN,Action,Unknown,0.00,0.01,0.00,0.00,0.01

In [ ]:
df.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

#Filling Games with missing years with authentic data by using Wikipedia API

In [ ]:
def getReleaseYear(game_name,search_for):
    headers = {
        "User-Agent": "FetchVideoGameInfo(ssjmukherjee@gmail.com)"
    }
    search_url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action":"query",
        "list":"search",
        "srsearch":game_name + " video game",
        "format":"json"
    }
    #First proper video game name to be searched
    search_response = requests.get(search_url, params=params, headers=headers)
    data = search_response.json()

    #Fetching the top search result and passing that to the wiki page url. Also need to make sure to replace whitespace with _
    result = data.get("query", {}).get("search", [])
    if not result:
      print(f"No Wikipedia search results for {game_name}")
      return None
    page_title = data["query"]["search"][0]["title"]
    page_url = f"https://en.wikipedia.org/wiki/{page_title.replace(' ', '_')}"

    #Now fetching the page containing the game that we saerched
    response = requests.get(page_url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")
    infobox = soup.find("table", {"class": "infobox"})
    if not infobox:
      print(f"No infobox found for '{game_name}' ({page_title})")
      return None
    for row in infobox.find_all("tr"):
        header = row.find("th")
        if header and header.text.strip().lower() in [search_for, f'{search_for}d',f'{search_for}s']:  #publishers, released, releases
            value = row.find("td").get_text(separator=" ", strip=True)
            return value

    return f"No release info found for '{page_title}'."

#Looking games with null Year and populating the obtained year from Wiki
for idx, row in df[df["Year"].isna()].iterrows():
    game_name = row["Name"]
    year_description = getReleaseYear(game_name,"release")
    if year_description is None:
      continue
    year_arr=year_description.split(":")  #Most of the data has the format 'Country1 and Platform1 Relaesed Year1: Country2 and Platform2 Relaesed Year2'. Hence splittingwith
    year_pattern = re.compile(r'\b(19|20)\d{2}\b')
    year_parts = [year_str_element.strip() for year_str_element in year_arr if year_pattern.search(year_str_element)]
    if len(year_parts)>0:
      year_parts=year_parts[0]
      year = re.search(r'\b(19|20)\d{2}\b', year_parts)
      if year:
        print(year.group(0), ' ', float(year.group(0)))
        df.at[idx, "Year"] = float(year.group(0))

for idx, row in df[df["Publisher"].isna()].iterrows():
    game_name = row["Name"]
    publisher_str = getReleaseYear(game_name,"publisher")
    if publisher_str is None:
      continue
    df.at[idx, "Publisher"] = publisher_str

2003   2003.0
2008   2008.0
2004   2004.0
1978   1978.0
2007   2007.0
2001   2001.0
2008   2008.0
2003   2003.0
2007   2007.0
2025   2025.0
2007   2007.0
No infobox found for 'Triple Play 99' (Triple Play (video game series))
2011   2011.0
2008   2008.0
No infobox found for 'Adventure' (Adventure game)
1977   1977.0
2003   2003.0
2002   2002.0
2007   2007.0
1999   1999.0
1997   1997.0
2011   2011.0
1977   1977.0
2002   2002.0
2005   2005.0
2011   2011.0
2008   2008.0
2011   2011.0
2011   2011.0
2006   2006.0
2002   2002.0
2008   2008.0
2001   2001.0
2010   2010.0
2004   2004.0
2011   2011.0
2011   2011.0
2011   2011.0
2004   2004.0
2008   2008.0
2011   2011.0
2007   2007.0
2005   2005.0
2002   2002.0
2002   2002.0
2004   2004.0
2003   2003.0
1980   1980.0
2009   2009.0
1987   1987.0
2006   2006.0
1977   1977.0
2004   2004.0
1980   1980.0
2008   2008.0
1976   1976.0
2008   2008.0
2010   2010.0
2011   2011.0
2011   2011.0
2008   2008.0
2001   2001.0
2008   2008.0
1978   1978.0
2007   2007.0
2000   2000.0
2001   2001.0
2001   2001.0
2013   2013.0
1999   1999.0
2002   2002.0
2010   2010.0
1980   1980.0
2004   2004.0
2019   2019.0
No infobox found for 'Slot Machine' (Slot machine)
2007   2007.0
1979   1979.0
2008   2008.0
2010   2010.0
2006   2006.0
2002   2002.0
2005   2005.0
2002   2002.0
2004   2004.0
1977   1977.0
2005   2005.0
2011   2011.0
2008   2008.0
2005   2005.0
1993   1993.0
2007   2007.0
2010   2010.0
2010   2010.0
2006   2006.0
2008   2008.0
2002   2002.0
2002   2002.0
2010   2010.0
2011   2011.0
No infobox found for 'Yu Yu Hakusho: Dark Tournament' (List of Yu Yu Hakusho video games)
2009   2009.0
No infobox found for 'Breakaway IV' (Video game industry)
2002   2002.0
2011   2011.0
1997   1997.0
2013   2013.0
2011   2011.0
2009   2009.0
2006   2006.0
2010   2010.0
2010   2010.0
2001   2001.0
2011   2011.0
2025   2025.0
2005   2005.0
2010   2010.0
2002   2002.0
2002   2002.0
1988   1988.0
2001   2001.0
2013   2013.0
2011   2011.0
1978   1978.0
2002   2002.0
2004   2004.0
2006   2006.0
2000   2000.0
2000   2000.0
2000   2000.0
2001   2001.0
2008   2008.0
2003   2003.0
2012   2012.0
2009   2009.0
2006   2006.0
2002   2002.0
2002   2002.0
2020   2020.0
2011   2011.0
2006   2006.0
2006   2006.0
2007   2007.0
2003   2003.0
2006   2006.0
2006   2006.0
No infobox found for 'Atsumare! Power Pro Kun no DS Koushien' (List of Konami games)
2007   2007.0
2006   2006.0
2020   2020.0
1988   1988.0
2008   2008.0
2005   2005.0
2023   2023.0
1996   1996.0
2006   2006.0
No infobox found for 'Charm Girls Club: My Fashion Show' (Fashion doll)
2010   2010.0
2008   2008.0
No infobox found for 'The Hidden' (The Hidden (video game))
2008   2008.0
2013   2013.0
2000   2000.0
2023   2023.0
1993   1993.0
2004   2004.0
2003   2003.0
2012   2012.0
2007   2007.0
2006   2006.0
No infobox found for 'National Geographic Challenge!' (National Geographic Video)
2012   2012.0
No Wikipedia search results for Prinny: Can I Really Be The Hero? (US sales)
2005   2005.0
2011   2011.0
2010   2010.0
2008   2008.0
2019   2019.0
2011   2011.0
2003   2003.0
2011   2011.0
2005   2005.0
1988   1988.0
2007   2007.0
2007   2007.0
1999   1999.0
2019   2019.0
No infobox found for 'B.L.U.E.: Legend of Water' (List of video game publishers)
2006   2006.0
2003   2003.0
1995   1995.0
2010   2010.0
1991   1991.0
2009   2009.0
No infobox found for 'Clockwork Empires' (2025 in video games)
No infobox found for 'Housekeeping' (Video games in the United States)
2008   2008.0
1984   1984.0
2012   2012.0
2009   2009.0
2006   2006.0
2005   2005.0
1988   1988.0
2002   2002.0
2002   2002.0
1989   1989.0
2004   2004.0
2003   2003.0
No infobox found for 'Umineko no Naku Koro ni San: Shinjitsu to Gensou no Yasoukyoku' (List of PlayStation 3 games (Q–Z))
2002   2002.0
No infobox found for 'Payout Poker & Casino' (Video poker)
2002   2002.0
2022   2022.0
2008   2008.0
2000   2000.0
2009   2009.0
No infobox found for 'Yu-Gi-Oh! 5D's Wheelie Breakers (JP sales)' (List of Yu-Gi-Oh! video games)
2006   2006.0
2009   2009.0
2004   2004.0
2005   2005.0
2025   2025.0
2010   2010.0
2003   2003.0
1999   1999.0
2007   2007.0
2010   2010.0
2003   2003.0
1999   1999.0
2015   2015.0
2007   2007.0
2003   2003.0
2012   2012.0
2011   2011.0
2004   2004.0
2011   2011.0
No infobox found for 'Triple Play 99' (Triple Play (video game series))
No infobox found for 'Yu Yu Hakusho: Dark Tournament' (List of Yu Yu Hakusho video games)
No infobox found for 'Disney Channel Collection Vol. 1' (List of Disney Channel original films)
No infobox found for 'Atsumare! Power Pro Kun no DS Koushien' (List of Konami games)
No infobox found for 'Cartoon Network Collection: Game Boy Advance Video Volume 2' (List of Game Boy Advance games)
No Wikipedia search results for Prinny: Can I Really Be The Hero? (US sales)
No infobox found for 'B.L.U.E.: Legend of Water' (List of video game publishers)
No infobox found for 'Housekeeping' (Video games in the United States)
No infobox found for 'Silverlicious' (List of Nintendo DS games (J–P))
No infobox found for 'Umineko no Naku Koro ni San: Shinjitsu to Gensou no Yasoukyoku' (List of PlayStation 3 games (Q–Z))
No Wikipedia search results for Moshi, Kono Sekai ni Kami-sama ga Iru to suru Naraba.

In [ ]:
df.isnull().sum()

Rank             0
Name             0
Platform         0
Year            51
Genre            0
Publisher       11
NA_Sales         0
EU_Sales         0
JP_Sales         0
Other_Sales      0
Global_Sales     0
dtype: int64

Now we can remove the 49 missing Year data and 10 missing Publisher data

In [ ]:
df.dropna(subset=['Year'], inplace=True)
df.dropna(subset=['Publisher'], inplace=True)
df.isnull().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16543 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16543 non-null  int64
 1   Name          16543 non-null  object
 2   Platform      16543 non-null  object
 3   Year          16543 non-null  float64
 4   Genre         16543 non-null  object
 5   Publisher     16543 non-null  object
 6   NA_Sales      16543 non-null  float64
 7   EU_Sales      16543 non-null  float64
 8   JP_Sales      16543 non-null  float64
 9   Other_Sales   16543 non-null  float64
 10  Global_Sales  16543 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.5+ MB

In [ ]:
def getReleaseYear(game_name):
    headers = {
        "User-Agent": "FetchVideoGameInfo(ssjmukherjee@gmail.com)"
    }
    search_url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action":"query",
        "list":"search",
        "srsearch":game_name + " video game",
        "format":"json"
    }
    #First proper video game name to be searched
    search_response = requests.get(search_url, params=params, headers=headers)
    data = search_response.json()

    #Fetching the top search result and passing that to the wiki page url. Also need to make sure to replace whitespace with _
    result = data.get("query", {}).get("search", [])
    if not result:
      print(f"No Wikipedia search results for {game_name}")
      return None
    page_title = data["query"]["search"][0]["title"]
    page_url = f"https://en.wikipedia.org/wiki/{page_title.replace(' ', '_')}"

    #Now fetching the page containing the game that we saerched
    response = requests.get(page_url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")
    infobox = soup.find("table", {"class": "infobox"})
    if not infobox:
      print(f"No infobox found for '{game_name}' ({page_title})")
      return None
    for row in infobox.find_all("tr"):
        print(row)
        header = row.find("th")
        if header and header.text.strip().lower() in ["publisher","publishers"]:
            value = row.find("td").get_text(separator=" ", strip=True)
            return value

    return f"No release info found for '{page_title}'."

#Looking games with null Year and populating the obtained year from Wiki
getReleaseYear("Witcher 3")

<tr><th class="infobox-above fn" colspan="2" style="font-size:125%;font-style:italic;">The Witcher</th></tr>
<tr><td class="infobox-image" colspan="2"><span class="mw-default-size" typeof="mw:File/Frameless"><a class="mw-file-description" href="/wiki/File:The_Witcher_video_game_series_logo.png"><img class="mw-file-element" data-file-height="206" data-file-width="483" decoding="async" height="124" src="//upload.wikimedia.org/wikipedia/en/thumb/5/53/The_Witcher_video_game_series_logo.png/330px-The_Witcher_video_game_series_logo.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/5/53/The_Witcher_video_game_series_logo.png/435px-The_Witcher_video_game_series_logo.png 1.5x, //upload.wikimedia.org/wikipedia/en/5/53/The_Witcher_video_game_series_logo.png 2x" width="290"/></a></span><div class="infobox-caption">Logo since 2015</div></td></tr>
<tr><th class="infobox-label" scope="row" style="white-space:nowrap;padding-right:0.65em;"><a href="/wiki/Video_game_genre" title="Video game genre">Genres</a></th><td class="infobox-data"><a href="/wiki/Action_role-playing_game" title="Action role-playing game">Action role-playing</a><br/><a href="/wiki/Digital_tabletop_game" title="Digital tabletop game">Digital tabletop game</a><br/><a href="/wiki/Multiplayer_online_battle_arena" title="Multiplayer online battle arena">Multiplayer online battle arena</a><br/><a href="/wiki/Digital_collectible_card_game" title="Digital collectible card game">Digital collectible card game</a></td></tr>
<tr><th class="infobox-label" scope="row" style="white-space:nowrap;padding-right:0.65em;"><a href="/wiki/Video_game_developer" title="Video game developer">Developers</a></th><td class="infobox-data"><a class="mw-redirect" href="/wiki/CD_Projekt_Red" title="CD Projekt Red">CD Projekt Red</a><br/>Breakpoint<br/>Can Explode Games<br/>Fuero Games<br/>Spokko</td></tr>
<tr><th class="infobox-label" scope="row" style="white-space:nowrap;padding-right:0.65em;"><a href="/wiki/Video_game_publisher" title="Video game publisher">Publishers</a></th><td class="infobox-data"><style data-mw-deduplicate="TemplateStyles:r1126788409">.mw-parser-output .plainlist ol,.mw-parser-output .plainlist ul{line-height:inherit;list-style:none;margin:0;padding:0}.mw-parser-output .plainlist ol li,.mw-parser-output .plainlist ul li{margin-bottom:0}</style><div class="plainlist"><ul><li>CD Projekt</li><li><a class="mw-redirect" href="/wiki/Atari,_Inc._(1993%E2%80%93present)" title="Atari, Inc. (1993–present)">Atari</a> <span style="font-size: 85%;">(2007–2011)</span></li><li><a href="/wiki/Warner_Bros._Games" title="Warner Bros. Games">Warner Bros. Games</a> <span style="font-size: 85%;">(2012-present)</span></li><li><a href="/wiki/Bandai_Namco_Entertainment" title="Bandai Namco Entertainment">Bandai Namco Entertainment</a> <span style="font-size: 85%;">(2012-present)</span></li><li>Hands-On Mobile</li><li>Spokko</li></ul></div></td></tr>

'CD Projekt Atari (2007–2011) Warner Bros. Games (2012-present) Bandai Namco Entertainment (2012-present) Hands-On Mobile Spokko'

In [ ]:
df.dropna(subset=['Name'], inplace=True)
df.isnull().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

Converting Year into Integer

In [ ]:
df['Year']=df['Year'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16543 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16543 non-null  int64
 1   Name          16543 non-null  object
 2   Platform      16543 non-null  object
 3   Year          16543 non-null  int64
 4   Genre         16543 non-null  object
 5   Publisher     16543 non-null  object
 6   NA_Sales      16543 non-null  float64
 7   EU_Sales      16543 non-null  float64
 8   JP_Sales      16543 non-null  float64
 9   Other_Sales   16543 non-null  float64
 10  Global_Sales  16543 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 1.5+ MB

In [ ]:
df['Platform'].unique()

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       '3DS', 'PS4', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne', 'GC',
       'WiiU', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

We have to group the platforms

In [ ]:
platformCategory={
    "Nintendo":["NES","SNES","N64","Wii","WiiU","GB","GBA","GC","DS","3DS"],
    "PS":["PS","PS3","PSP","PS4","PS2","PSV"],
    "XBox":["X360","XB","XOne"],
    "PC":["PC", "2600", "3DO", "NG", "TG16", "WS", "PCFX"],
    "Sega":["GEN", "SCD", "SAT", "DC","GG"]
    }
#We need to re-order the platformCategory into Platform:Category
platformCategory={platform:platGroup for platGroup,platformList in platformCategory.items() for platform in platformList}
platformCategory

{'NES': 'Nintendo',
 'SNES': 'Nintendo',
 'N64': 'Nintendo',
 'Wii': 'Nintendo',
 'WiiU': 'Nintendo',
 'GB': 'Nintendo',
 'GBA': 'Nintendo',
 'GC': 'Nintendo',
 'DS': 'Nintendo',
 '3DS': 'Nintendo',
 'PS': 'PS',
 'PS3': 'PS',
 'PSP': 'PS',
 'PS4': 'PS',
 'PS2': 'PS',
 'PSV': 'PS',
 'X360': 'XBox',
 'XB': 'XBox',
 'XOne': 'XBox',
 'PC': 'PC',
 '2600': 'PC',
 '3DO': 'PC',
 'NG': 'PC',
 'TG16': 'PC',
 'WS': 'PC',
 'PCFX': 'PC',
 'GEN': 'Sega',
 'SCD': 'Sega',
 'SAT': 'Sega',
 'DC': 'Sega',
 'GG': 'Sega'}

In [ ]:
df['Platform Group']=df['Platform'].map(platformCategory)
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Platform Group
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,Nintendo
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,Nintendo
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,Nintendo
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,Nintendo
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,Nintendo

In [ ]:
df.isnull().sum()

Rank              0
Name              0
Platform          0
Year              0
Genre             0
Publisher         0
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
Platform Group    0
dtype: int64

In [ ]:
col_position = df.columns.get_loc('Platform') + 1  # right after 'Platform'
df.insert(col_position, 'Platform Group', df.pop('Platform Group'))

In [ ]:
df.columns

Index(['Rank', 'Name', 'Platform', 'Platform Group', 'Year', 'Genre',
       'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales',
       'Global_Sales'],
      dtype='object')

Renaming the columns

In [ ]:
df.rename(columns={'NA_Sales':'NA Sales','EU_Sales':'EU Sales','JP_Sales':'JP Sales','Other_Sales':'Other Sales','Global_Sales':'Global Sales','Critic_Score':'Critic Score','Critic_Count':'Critic Count','User_Score':'User Score','User_Count':'User Count'}, inplace=True)
df.columns

Index(['Rank', 'Name', 'Platform', 'Platform Group', 'Year', 'Genre',
       'Publisher', 'NA Sales', 'EU Sales', 'JP Sales', 'Other Sales',
       'Global Sales'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16543 entries, 0 to 16597
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rank            16543 non-null  int64
 1   Name            16543 non-null  object
 2   Platform        16543 non-null  object
 3   Platform Group  16543 non-null  object
 4   Year            16543 non-null  int64
 5   Genre           16543 non-null  object
 6   Publisher       16543 non-null  object
 7   NA Sales        16543 non-null  float64
 8   EU Sales        16543 non-null  float64
 9   JP Sales        16543 non-null  float64
 10  Other Sales     16543 non-null  float64
 11  Global Sales    16543 non-null  float64
dtypes: float64(5), int64(2), object(5)
memory usage: 1.6+ MB

Converting Year of Release into Integer

In [ ]:
df['Year']=df['Year'].astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16543 entries, 0 to 16597
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rank            16543 non-null  int64
 1   Name            16543 non-null  object
 2   Platform        16543 non-null  object
 3   Platform Group  16543 non-null  object
 4   Year            16543 non-null  int64
 5   Genre           16543 non-null  object
 6   Publisher       16543 non-null  object
 7   NA Sales        16543 non-null  float64
 8   EU Sales        16543 non-null  float64
 9   JP Sales        16543 non-null  float64
 10  Other Sales     16543 non-null  float64
 11  Global Sales    16543 non-null  float64
dtypes: float64(5), int64(2), object(5)
memory usage: 1.6+ MB

In [ ]:
df.to_csv("Video_Games_Sales_Cleaned_1.csv", index=False)
files.download("Video_Games_Sales_Cleaned_1.csv")